import type { MissionState } from "./types";

export const initialMission: MissionState = {
  id: "NX-042",
  title: "自主发布 Agent 协作平台",
  objective:
    "研究领先多 Agent 产品，形成可验证的产品方案，完成实现、质量评审与发布准备。",
  mode: "collaborate",
  running: false,
  cycle: 18,
  riskBudget: 32,
  agents: [
    {
      id: "atlas",
      name: "Atlas",
      initials: "AT",
      role: "任务指挥官",
      specialty: "目标拆解、动态路由、冲突仲裁",
      color: "#e9ff70",
      status: "working",
      trust: 96,
      load: 74,
      memoryCount: 128,
    },
    {
      id: "sift",
      name: "Sift",
      initials: "SF",
      role: "研究 Agent",
      specialty: "证据检索、来源评级、竞品归纳",
      color: "#61d7c8",
      status: "working",
      trust: 93,
      load: 68,
      memoryCount: 214,
    },
    {
      id: "forge",
      name: "Forge",
      initials: "FG",
      role: "构建 Agent",
      specialty: "系统设计、实现、运行时集成",
      color: "#ff9d66",
      status: "idle",
      trust: 91,
      load: 42,
      memoryCount: 96,
    },
    {
      id: "prism",
      name: "Prism",
      initials: "PR",
      role: "体验 Agent",
      specialty: "交互架构、信息密度、无障碍",
      color: "#9db7ff",
      status: "idle",
      trust: 94,
      load: 36,
      memoryCount: 147,
    },
    {
      id: "warden",
      name: "Warden",
      initials: "WD",
      role: "独立审查 Agent",
      specialty: "安全、质量门禁、反事实检查",
      color: "#ffcf5a",
      status: "reviewing",
      trust: 98,
      load: 55,
      memoryCount: 183,
    },
  ],
  tasks: [
    {
      id: "T-101",
      title: "竞品机制研究",
      summary: "提取 Raft、Multica、AI Town 与主流编排框架的可复用机制。",
      status: "running",
      agentId: "sift",
      dependsOn: [],
      progress: 72,
      confidence: 94,
      risk: 8,
      attempts: 1,
      artifact: "research/landscape.md",
    },
    {
      id: "T-102",
      title: "协作协议设计",
      summary: "定义任务图、消息交接、共享状态、权限和失败恢复协议。",
      status: "backlog",
      agentId: "atlas",
      dependsOn: ["T-101"],
      progress: 0,
      confidence: 91,
      risk: 18,
      attempts: 0,
      artifact: "spec/orchestration.md",
    },
    {
      id: "T-103",
      title: "控制台体验",
      summary: "构建低认知负担的任务、团队、证据与记忆可视界面。",
      status: "backlog",
      agentId: "prism",
      dependsOn: ["T-102"],
      progress: 0,
      confidence: 90,
      risk: 14,
      attempts: 0,
      artifact: "app/control-plane",
    },
    {
      id: "T-104",
      title: "任务图引擎",
      summary: "实现依赖调度、并行执行、重试、暂停和可恢复检查点。",
      status: "backlog",
      agentId: "forge",
      dependsOn: ["T-102"],
      progress: 0,
      confidence: 88,
      risk: 27,
      attempts: 0,
      artifact: "runtime/graph-engine",
    },
    {
      id: "T-105",
      title: "集成与验收",
      summary: "把控制台与任务引擎合并，通过行为测试与视觉验收。",
      status: "backlog",
      agentId: "forge",
      dependsOn: ["T-103", "T-104"],
      progress: 0,
      confidence: 86,
      risk: 24,
      attempts: 0,
      artifact: "evidence/acceptance",
    },
    {
      id: "T-106",
      title: "独立红队评审",
      summary: "检查越权执行、证据缺口、脆弱依赖和虚假完成。",
      status: "backlog",
      agentId: "warden",
      dependsOn: ["T-105"],
      progress: 0,
      confidence: 97,
      risk: 42,
      attempts: 0,
      requiresApproval: true,
      artifact: "evidence/red-team.md",
    },
    {
      id: "T-107",
      title: "发布决策",
      summary: "汇总证据、成本、剩余风险，生成可审计的发布收据。",
      status: "backlog",
      agentId: "atlas",
      dependsOn: ["T-106"],
      progress: 0,
      confidence: 95,
      risk: 20,
      attempts: 0,
      requiresApproval: true,
      artifact: "release/receipt.json",
    },
  ],
  events: [
    {
      id: "E-18",
      cycle: 18,
      agentId: "sift",
      kind: "progress",
      message: "完成 8 个官方来源交叉验证，已排除 3 条二手营销结论。",
    },
    {
      id: "E-17",
      cycle: 17,
      agentId: "warden",
      kind: "review",
      message: "要求所有“完成”状态必须绑定产物路径与验证结果。",
    },
    {
      id: "E-16",
      cycle: 16,
      agentId: "atlas",
      kind: "claim",
      message: "将研究任务交给 Sift，设置 95% 来源覆盖门槛。",
    },
    {
      id: "E-15",
      cycle: 15,
      agentId: "atlas",
      kind: "system",
      message: "任务图已建立，风险预算限制为 32。",
    },
  ],
  memories: [
    {
      id: "M-44",
      agentId: "sift",
      title: "持久身份优于临时会话",
      detail: "Agent 的角色、记忆、频道与工作区应跨运行保留，运行会话只是一种执行载体。",
      importance: 96,
      cycle: 17,
      tags: ["identity", "raft"],
    },
    {
      id: "M-43",
      agentId: "warden",
      title: "评审 Agent 必须独立",
      detail: "实现者不能自证完成；高风险任务需要独立上下文和显式通过证据。",
      importance: 98,
      cycle: 16,
      tags: ["quality", "governance"],
    },
    {
      id: "M-42",
      agentId: "atlas",
      title: "共享状态必须事务化",
      detail: "所有任务状态变化写入不可变事件账本，再投影为当前视图，避免并发覆盖。",
      importance: 94,
      cycle: 15,
      tags: ["state", "ai-town"],
    },
  ],
};
